SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 700
FPS  = 60
GAME_CAPTION = "Game đoán từ vip pro made by duyanhle"
DEFAULT_BACKGROUND_COLOR = (255, 255, 255)

#load data
DATA_FILE_NAME = "data.json"
IMAGES_HINT_PATH = "datapacks/hint/images/"
TEXT_HINT_PATH = "datapacks/hint/text/"

#logger
LOAD_DATA_LOG_NAME = "Word-Guessing.core.loadData"

#hintFrame
HINT_FRAME_PERCENT = 80/100
HINT_FRAME_TEXT_FONT_PATH = "assets/font/DFVN-Excalifont.ttf"
HINT_FRAME_TEXT_SIZE = 22
HINT_FRAME_TEXT_COLOR = (0,0,0) #black
HINT_FRAME_LOADING_IMAGE_PATH = "assets/images/loading.jpg"

#hint| forward and back  button
HINT_BUTTON_FONT = "arial"
HINT_BUTTON_TEXT_SIZE = 24
HINT_BUTTON_WIDTH_PERCENT = 1/10
HINT_BUTTON_HEIGHT_PERCENT = 2/35
HINT_BUTTON_BORDER_RADIUS = 8
HINT_FORWARD_BUTTON_COLOR = (0, 100, 255)
HINT_BACK_BUTTON_COLOR = (0, 200, 100)
HINT_BUTTON_TITLE_COLOR = (255, 255, 255)
HINT_FORWARD_BUTTON_CONTENT = "Forward"
HINT_BACK_BUTTON_CONTENT = "Back"
HINT_FORWARD_BUTTON_X_PERCENT = 30/100
HINT_FORWARD_BUTTON_Y_PERCENT = 88/100
HINT_BACK_BUTTON_X_PERCENT = 10/100
HINT_BACK_BUTTON_Y_PERCENT = 88/100

#label | display level
LEVEL_LABLE_CONTENT = "<#35457b>Mức độ </><#000000>:</>"
LEVEL = [0,1,2] #0:easy 1:medium 2:hard
LEVEL_TEXTS = ["<#45953f>Dễ</>","<#eea90c>Trung bình</>","<#ed3609>Khó</>"] #green,yellow,read
LEVEL_LABLE_TEXT_FONT_PATH = "assets/font/DFVN-Excalifont.ttf"
LEVEL_LABEL_TEXT_SIZE = 24
LEVEL_LABEL_DEFAULT_TEXT_COLOR = (0,0,0)
LEVEL_LABEL_BG_COLOR = (119,207,202,100)
LEVEL_LABEL_WIDTH_PERCENT = 1/6
LEVEL_LABEL_HEIGHT_PERCENT = 1/14
LEVEL_LABLE_X_PERCENT = 70/100
LEVEL_LABLE_Y_PERCENT = 6/100



